---
development:
  cloud_name: du9rwn7tg
  api_key: '895216944477945'
  api_secret: ZB8C_bYf40NSiQ6QmZ5X4Wb2m8g
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: du9rwn7tg
  api_key: '895216944477945'
  api_secret: ZB8C_bYf40NSiQ6QmZ5X4Wb2m8g
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: du9rwn7tg
  api_key: '895216944477945'
  api_secret: ZB8C_bYf40NSiQ6QmZ5X4Wb2m8g
  enhance_image_tag: true
  static_image_support: false
